version: "3"  
services:
  web:
    image: nginx:latest
    container_name: "land_web"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend-angular/dist:/usr/share/nginx/html:ro
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        #- ./data/img/:/usr/share/nginx/html/img/:rw
  db:
    image: mongo:4.4
    command: --quiet --logpath /dev/null
    container_name: "land_db"
      #volumes:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=land
  backend:
    image: node:14-alpine
    container_name: "land_backend"
    working_dir: /home/node/app
    volumes: 
      - ./backend-express:/home/node/app
      - ./data/img/:/home/node/app/img
    command: sh ./.startnode.sh ${PROD}
  dev:
    image: node:14-alpine
    container_name: "land_dev"
    working_dir: /home/node/app
    volumes:
      - ./frontend-angular:/home/node/app
    command: sh ./.startnode.sh ${PROD}
